export const CATEGORIES = [
  { id: "Access_Control",        display: "Access Control",        prefix: "ACC",     checkCount: 45 },
  { id: "Advanced_Security",     display: "Advanced Security",     prefix: "ADV",     checkCount: 10 },
  { id: "Authentication",        display: "Authentication",        prefix: "AUTH",    checkCount: 33 },
  { id: "Azure_AD_Integration",  display: "Azure AD Integration",  prefix: "AAD",     checkCount: 42 },
  { id: "Backup_Recovery",       display: "Backup Recovery",       prefix: "BCK",     checkCount: 8  },
  { id: "Certificate_Services",  display: "Certificate Services",  prefix: "CERT",    checkCount: 53 },
  { id: "Compliance",            display: "Compliance",            prefix: "COMPLY",  checkCount: 20 },
  { id: "Computer_Management",   display: "Computer Management",   prefix: "CMGMT",   checkCount: 37 },
  { id: "Computers_Servers",     display: "Computers & Servers",   prefix: "CMP",     checkCount: 30 },
  { id: "Domain_Configuration",  display: "Domain Configuration",  prefix: "DCONF",   checkCount: 31 },
  { id: "Domain_Controllers",    display: "Domain Controllers",    prefix: "DC",      checkCount: 39 },
  { id: "Group_Policy",          display: "Group Policy",          prefix: "GPO",     checkCount: 50 },
  { id: "Infrastructure",        display: "Infrastructure",        prefix: "INFRA",   checkCount: 33 },
  { id: "Kerberos_Security",     display: "Kerberos Security",     prefix: "KRB",     checkCount: 45 },
  { id: "LDAP_Security",         display: "LDAP Security",         prefix: "LDAP",    checkCount: 15 },
  { id: "Network_Security",      display: "Network Security",      prefix: "NET",     checkCount: 10 },
  { id: "PKI_Services",          display: "PKI Services",          prefix: "PKI",     checkCount: 30 },
  { id: "Persistence_Detection", display: "Persistence Detection", prefix: "PERS",    checkCount: 12 },
  { id: "Privileged_Access",     display: "Privileged Access",     prefix: "PRV",     checkCount: 32 },
  { id: "Published_Resources",   display: "Published Resources",   prefix: "PUBRES",  checkCount: 30 },
  { id: "SMB_Security",          display: "SMB Security",          prefix: "SMB",     checkCount: 12 },
  { id: "Security_Accounts",     display: "Security Accounts",     prefix: "SECACCT", checkCount: 30 },
  { id: "Service_Accounts",      display: "Service Accounts",      prefix: "SVC",     checkCount: 31 },
  { id: "Trust_Management",      display: "Trust Management",      prefix: "TMGMT",   checkCount: 32 },
  { id: "Trust_Relationships",   display: "Trust Relationships",   prefix: "TRST",    checkCount: 30 },
  { id: "Users_Accounts",        display: "Users & Accounts",      prefix: "USR",     checkCount: 32 },
  { id: "Users_and_Accounts",    display: "Users and Accounts",    prefix: "USR",     checkCount: 3  },
];

export const ENGINES = [
  { id: "adsi",       label: "ADSI",       file: "adsi.ps1",                 runner: "powershell",
    desc: "Pure .NET DirectorySearcher. No modules required. Fastest." },
  { id: "powershell", label: "PowerShell", file: "powershell.ps1",           runner: "powershell",
    desc: "Requires ActiveDirectory RSAT module (Get-ADObject)." },
  { id: "csharp",     label: "C#",         file: "csharp.cs",                runner: "csharp",
    desc: "Compiled .NET. Requires csc.exe (Framework) or dotnet SDK." },
  { id: "cmd",        label: "CMD",        file: "cmd.bat",                  runner: "cmd",
    desc: "Legacy CMD fallback. Uses dsquery and net commands." },
  { id: "combined",   label: "Combined",   file: "combined_multiengine.ps1", runner: "powershell",
    desc: "Auto-selects best available engine with graceful fallback." },
];
